# Describes the format for available zha services

permit:
  description: Allow nodes to join the ZigBee network.
  fields:
    duration:
      description: Time to permit joins, in seconds
      example: 60

remove:
  description: remove node(s) from the ZigBee network.
  fields:
    ieee:
      description: ieee or parts of it
      example: 00:15:8d:00:01:f4:66:c1
    nwk:
      description: nwk id of the device
      example: 1234

command:
  description: send a zigbee command to an entity, command write_attribute, tbd
  fields:
    entity_id:
      description: entity_id
    command:
      description: write_attribute
      example:  valid commands write_attribute
    cluster:
      description: cluster
    attribute:
      description: attribute
    value: 
      description: value
    mfgid:
      description: optional manufacturer ID
      
